version: 0.2
phases: 
  install: 
    runtime-versions:
        nodejs: 10
    commands: 
      - echo installing nodemodules 
      - npm install
      - npm install -g @angular/cli 
  build:
    commands:
      - echo build start 
      - ng build
  post_build:
    commands: 
      - echo S3 bucket 
      - aws s3 cp s3://codepipeline-us-east-2-619763825478/test1234 --recursive 
      - echo Build completes on `date`
  
 
