version: 0.2
phases: 
  install: 
    runtime-versions:
        nodejs: 10
  pre_build:       
    commands: 
      - echo installing nodemodules 
      - npm install
      - npm install -g @angular/cli 
  build:
    commands:
      - echo build start 
      - ng build
  post_build:
    commands:
      - echo Build completed on `data`
      
artifacts:
  files: 
      - '**/*'  
      - AppSpec.yml    
  base-directory: dist
discard-paths: no 
  
      
